
export const teamAbbreviations = {
  ARI: 'Diamondbacks',
  ATL: 'Braves',
  BAL: 'Orioles',
  BOS: 'Red Sox',
  CHC: 'Cubs',
  CIN: 'Reds',
  CLE: 'Guardians',
  COL: 'Rockies',
  CHW: 'White Sox',
  DET: 'Tigers',
  HOU: 'Astros',
  KCR: 'Royals',
  LAA: 'Angels',
  LAD: 'Dodgers',
  MIA: 'Marlins',
  MIL: 'Brewers',
  MIN: 'Twins',
  NYM: 'Mets',
  NYY: 'Yankees',
  Athletics: 'Athletics',
  PHI: 'Phillies',
  PIT: 'Pirates',
  SDP: 'Padres',
  SEA: 'Mariners',
  SFG: 'Giants',
  STL: 'Cardinals',
  TBR: 'Rays',
  TEX: 'Rangers',
  TOR: 'Blue Jays',
  WSH: 'Nationals',
};